[package]
name = "empiresim"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = "5.5.1"
simulation = { path = "../simulation" }
noise = "0.9.0"
rand = "0.9.1"

[dev-dependencies]
rand = "0.9.1"
